#!/usr/bin/env python3
"""
Convert a PNG (or any binary file) to a C header with a byte array.

Usage:
  python3 png_to_header.py input.png output.h

This writes a header defining `empty_scene_icon_png` and `empty_scene_icon_png_len`.
"""
import sys
import os

def to_c_array(data, varname='empty_scene_icon_png'):
    lines = []
    lines.append('static const unsigned char %s[] = {' % varname)
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        line = ', '.join('0x%02x' % b for b in chunk)
        lines.append('    ' + line + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    if len(sys.argv) != 3:
        print('Usage: png_to_header.py input.png output.h')
        return 1
    inp = sys.argv[1]
    out = sys.argv[2]
    if not os.path.exists(inp):
        print('Input file not found:', inp)
        return 1
    data = open(inp, 'rb').read()
    arr = to_c_array(data)
    with open(out, 'w') as f:
        f.write('// Generated by png_to_header.py from %s\n' % os.path.basename(inp))
        f.write('#pragma once\n\n')
        f.write(arr + '\n\n')
        f.write('static const unsigned int empty_scene_icon_png_len = %d;\n' % len(data))
    print('Wrote', out)
    return 0

if __name__ == '__main__':
    sys.exit(main())
